version: '3'

services:
  scout-be:
    tty: true
    ports:
      - "8000:8000"
    command: uvicorn main:app --reload --host 0.0.0.0
    build:
      dockerfile: Dockerfile
      context: backend
    env_file:
      - ./backend/.env
  
  scout-fe:
    tty: true
    ports:
      - "8080:8080"
    command: npm run serve
    build:
      dockerfile: Dockerfile
      context: frontend