version: '3.1'

services:
  scout-be:
    tty: true
    ports:
      - "8000:8000"
    command: uvicorn main:app --reload --host 0.0.0.0
    build:
      dockerfile: Dockerfile
      context: backend
    env_file:
      - ./backend/.env
      - ./.env
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
  
  scout-db:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - MONGO_URI=mongodb://mongo:27017
    depends_on:
      - mongo

  # scout-fe:
  #   tty: true
  #   ports:
  #     - "8080:8080"
  #   command: npm run serve
  #   build:
  #     dockerfile: Dockerfile
  #     context: frontend

  # scout-contracts:
  #   tty: true
  #   ports:
  #     - "8545:8545"
  #   command: npx hardhat node
  #   build:
  #     dockerfile: Dockerfile
  #     context: contracts